// Capa curada — contenido en español, etiquetas y correcciones sobre los datos de yoga-api.
// fuente:
//   "yoga-api"          -> nombre/beneficios vienen de la base; cues ES redactadas aquí
//   "yoga-api+propia"   -> base con datos flojos; cues y/o beneficios reescritos
//   "propia"            -> postura añadida a mano (no está en la base); revisar con criterio de maestra
//
// Vocabularios controlados (ver _pipeline/build.mjs para la validación):
//   tipo:     de pie, sentada, arrodillada, supina, prona, invertida, equilibrio, equilibrio de brazos, restaurativa
//   zona:     caderas, isquiotibiales, cuádriceps, ingles, psoas, columna, zona lumbar, hombros, pecho, cuello, core, muñecas, tobillos y pies, glúteos
//   dinamica: extensión de columna, flexión hacia adelante, flexión lateral, torsión, apertura de cadera, equilibrio, inversión, fuerza, quietud
//   tema:     enraizar, soltar, expansión, calma, energía, confianza, foco, corazón, transición

// Beneficios en español para las posturas cuya ficha viene de yoga-api (traducción/resumen
// del campo pose_benefits en inglés). Las posturas con `beneficios` inline no usan esto.
export const beneficiosES = {
  "navasana": ["Fortalece abdomen, flexores de cadera y columna.", "Estimula riñones, tiroides e intestinos.", "Mejora la digestión y ayuda a soltar el estrés."],
  "ardha-navasana": ["Fortalece abdomen, flexores de cadera y columna.", "Estimula riñones, tiroides e intestinos.", "Alivia el estrés y mejora la digestión."],
  "dhanurasana": ["Estira todo el frente del cuerpo: tobillos, muslos, ingles, abdomen, pecho y garganta.", "Estira el psoas y fortalece la musculatura de la espalda.", "Mejora la postura y estimula los órganos del abdomen."],
  "setu-bandha-sarvangasana": ["Estira pecho, cuello y columna.", "Estimula órganos abdominales, pulmones y tiroides.", "Reduce ansiedad, fatiga y dolor de espalda; alivia molestias menstruales con apoyo."],
  "baddha-konasana": ["Abre caderas e ingles.", "Estira hombros, caja torácica y espalda.", "Estimula órganos abdominales, pulmones y corazón."],
  "ustrasana": ["Estira todo el frente del cuerpo: tobillos, muslos, ingles, abdomen, pecho y garganta.", "Estira el psoas y fortalece la espalda.", "Mejora la postura y estimula los órganos del abdomen y el cuello."],
  "marjaryasana": ["Descarga columna y cuello.", "Da energía al cuerpo.", "Moviliza la espalda al ritmo de la respiración."],
  "bitilasana": ["Quita la fatiga.", "Mejora la respiración y la circulación hacia el cerebro.", "Revitaliza todo el cuerpo."],
  "utkatasana": ["Fortalece tobillos, muslos, gemelos y columna.", "Estira hombros y pecho.", "Estimula abdomen, diafragma y corazón; da energía."],
  "balasana": ["Estira suavemente caderas, muslos y tobillos.", "Calma la mente y alivia estrés y fatiga.", "Descarga espalda y cuello con la frente apoyada."],
  "bakasana": ["Fortalece brazos y muñecas.", "Estira la espalda alta y tonifica el abdomen.", "Abre las ingles y trabaja el foco mental."],
  "ardha-pincha-mayurasana": ["Calma la mente y alivia el estrés leve.", "Estira hombros, isquiotibiales, gemelos y manos.", "Fortalece brazos y piernas; ayuda a prevenir la osteoporosis."],
  "garudasana": ["Fortalece y estira tobillos y gemelos.", "Estira muslos, caderas, hombros y espalda alta.", "Mejora la concentración y el equilibrio."],
  "utthita-hasta-padangusthasana": ["Abre caderas e ingles.", "Estira isquiotibiales, banda iliotibial y piernas.", "Mejora el equilibrio."],
  "utthita-parsvakonasana": ["Fortalece y estira piernas, rodillas y tobillos.", "Estira ingle, columna, cintura, pecho, pulmones y hombros.", "Estimula los órganos abdominales y aumenta la resistencia."],
  "pincha-mayurasana": ["Fortalece brazos y hombros.", "Mejora el foco y el equilibrio.", "Estira la espalda alta y baja; tonifica el abdomen."],
  "uttanasana-hombros": ["Calma la mente y alivia el estrés.", "Estira isquiotibiales, gemelos y caderas.", "Abre los hombros y estimula hígado y riñones."],
  "ardha-chandrasana": ["Fortalece abdomen, tobillos, muslos, glúteos y columna.", "Estira ingles, isquiotibiales, gemelos, hombros y pecho.", "Mejora la coordinación y el equilibrio."],
  "adho-mukha-vrksasana": ["Fortalece hombros, brazos y muñecas.", "Estira el abdomen.", "Mejora el equilibrio y calma la mente."],
  "anjaneyasana": ["Estira pecho, pulmones, cuello, vientre y psoas.", "Fortalece hombros, brazos y espalda.", "Fortalece y estira muslos, gemelos y tobillos."],
  "supta-kapotasana": ["Estira isquiotibiales y cuádriceps.", "Abre glúteos y caderas.", "Descarga la zona lumbar sin cargar la espalda."],
  "eka-pada-rajakapotasana": ["Estira muslos, ingles (psoas), abdomen, pecho, hombros y cuello.", "Estimula los órganos abdominales.", "Abre hombros y pecho."],
  "phalakasana": ["Fortalece brazos, muñecas y columna.", "Tonifica el abdomen.", "Estabiliza todo el cuerpo como base del vinyasa."],
  "halasana": ["Calma la mente.", "Estimula órganos abdominales y tiroides.", "Estira hombros y columna; reduce estrés y fatiga."],
  "parsvottanasana": ["Calma la mente.", "Estira columna, hombros, caderas e isquiotibiales.", "Fortalece las piernas y mejora la postura y el equilibrio."],
  "parsva-virabhadrasana": ["Fortalece y estira piernas, rodillas y tobillos.", "Estira ingle, columna, cintura, pecho, pulmones y hombros.", "Estimula órganos abdominales y aumenta la resistencia."],
  "paschimottanasana": ["Calma la mente y alivia el estrés leve.", "Estira columna, hombros e isquiotibiales.", "Estimula hígado y riñones; mejora la digestión."],
  "padmasana": ["Abre caderas e ingles; estira rodillas, tobillos y muslos.", "Fortalece la espalda y calma la mente.", "Mejora la circulación en la pelvis."],
  "salamba-sarvangasana": ["Calma la mente y alivia el estrés leve.", "Estimula tiroides y órganos abdominales.", "Estira hombros y cuello; tonifica piernas y glúteos."],
  "vasisthasana": ["Fortalece brazos, muñecas y piernas.", "Estira la parte posterior de las piernas.", "Mejora el equilibrio y la concentración."],
  "salamba-bhujangasana": ["Fortalece la columna.", "Estira pecho, pulmones, hombros y abdomen.", "Estimula los órganos abdominales; abre el pecho."],
  "hanumanasana": ["Estira muslos, isquiotibiales e ingle.", "Estimula los órganos abdominales.", "Trabaja apertura profunda con foco y calma."],
  "malasana": ["Estira tobillos, ingles y espalda baja.", "Tonifica el vientre.", "Mejora la movilidad de cadera y tobillo."],
  "uttanasana": ["Calma la mente y alivia el estrés.", "Estimula hígado y riñones.", "Estira isquiotibiales, gemelos y caderas; reduce la fatiga."],
  "upavistha-konasana": ["Estira la cara interna y posterior de las piernas.", "Estimula los órganos abdominales.", "Fortalece la columna y calma la mente."],
  "vrksasana": ["Fortalece piernas, tobillos y pies.", "Mejora la flexibilidad de caderas y rodillas.", "Mejora el equilibrio y la concentración."],
  "trikonasana": ["Estira y fortalece muslos, rodillas y tobillos.", "Estira caderas, ingle, isquiotibiales, gemelos, hombros, pecho y columna.", "Estimula los órganos abdominales y ayuda a soltar el estrés."],
  "urdhva-mukha-svanasana": ["Mejora la postura.", "Fortalece columna, brazos y muñecas.", "Estira pecho, pulmones, hombros y abdomen."],
  "virabhadrasana-i": ["Estira pecho, pulmones, hombros, cuello, vientre y psoas.", "Fortalece hombros, brazos y espalda.", "Fortalece y estira muslos, gemelos y tobillos."],
  "virabhadrasana-ii": ["Fortalece y estira piernas y tobillos.", "Estira ingle, pecho, pulmones y hombros.", "Estimula órganos abdominales y aumenta la resistencia."],
  "virabhadrasana-iii": ["Fortalece tobillos y piernas.", "Fortalece hombros y espalda; tonifica el abdomen.", "Mejora el equilibrio y la postura."],
  "urdhva-dhanurasana": ["Fortalece brazos, muñecas, piernas, glúteos, abdomen y columna.", "Estimula tiroides e hipófisis.", "Da energía y contrarresta el decaimiento."],
  "camatkarasana": ["Estira pecho, hombros, espalda y garganta.", "Fortalece y abre caderas, flexores de cadera y muslos.", "Da energía y sensación de expansión."],
};

export const curado = [
  {
    slug: "navasana", apiId: 1, fuente: "yoga-api",
    es: "Postura del barco", en: "Boat", san: "Paripurna Navasana", trad: "nava = barco",
    nivel: "intermedio", tipo: ["sentada"], zona: ["core", "psoas", "columna"],
    dinamica: ["fuerza", "equilibrio"], tema: ["energía", "foco"],
    img: "Paripurna-Navasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Sentada, lleva el peso justo detrás de los isquiones y alarga la columna hacia arriba.",
      "Eleva las tibias paralelas al suelo; si la espalda se redondea, quédate con las rodillas dobladas.",
      "Estira los brazos hacia adelante a la altura de los hombros; pecho abierto, mirada al frente.",
    ],
    precaucion: ["Hernia de disco lumbar, embarazo o problemas de cuello: evítala o hazla con rodillas dobladas."],
  },
  {
    slug: "ardha-navasana", apiId: 2, fuente: "yoga-api",
    es: "Medio barco", en: "Half Boat", san: "Ardha Navasana", trad: "ardha = medio, nava = barco",
    nivel: "principiante", tipo: ["sentada"], zona: ["core", "psoas"],
    dinamica: ["fuerza"], tema: ["energía", "foco"], img: null,
    entrada: [
      "Sentada, sujeta la parte de atrás de los muslos con las rodillas dobladas a 90°.",
      "Lleva las espinillas hacia el abdomen y balancéate sobre los isquiones sin redondear la espalda.",
      "Alarga el frente del torso; el pecho sube, el abdomen se activa.",
    ],
    precaucion: ["Molestia lumbar o de cuello: apoya las manos en el suelo detrás de la cadera."],
  },
  {
    slug: "dhanurasana", apiId: 3, fuente: "yoga-api",
    es: "Postura del arco", en: "Bow", san: "Dhanurasana", trad: "dhanur = arco",
    nivel: "intermedio", tipo: ["prona"], zona: ["columna", "pecho", "cuádriceps", "psoas"],
    dinamica: ["extensión de columna", "apertura de cadera"], tema: ["expansión", "energía"],
    img: "Dhanurasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Boca abajo, dobla las rodillas al ancho de la cadera y sujeta los tobillos por fuera.",
      "Lleva los talones lejos de los glúteos: la pierna empuja contra la mano y eso abre el pecho.",
      "Rueda los hombros atrás; mirada al frente, cuello largo.",
    ],
    precaucion: ["Lesión lumbar o de cuello, hernia, presión arterial alta o baja, embarazo."],
  },
  {
    slug: "setu-bandha-sarvangasana", apiId: 4, fuente: "yoga-api",
    es: "Puente", en: "Bridge", san: "Setu Bandha Sarvangasana", trad: "setu = puente, bandha = cierre",
    nivel: "principiante", tipo: ["supina"], zona: ["columna", "pecho", "cuello", "glúteos", "cuádriceps"],
    dinamica: ["extensión de columna"], tema: ["expansión", "calma", "energía"], img: null,
    entrada: [
      "Boca arriba, pies al ancho de la cadera y cerca de los glúteos, paralelos.",
      "Empuja los pies contra el suelo y sube la pelvis; muslos paralelos entre sí.",
      "Entrelaza los dedos bajo la espalda y lleva los hombros uno hacia el otro; nuca larga en el suelo.",
    ],
    precaucion: ["Lesión de cuello: no gires la cabeza mientras estás en la postura."],
  },
  {
    slug: "baddha-konasana", apiId: 5, fuente: "yoga-api",
    es: "Postura del zapatero", en: "Bound Angle / Butterfly", san: "Baddha Konasana", trad: "baddha = atado, kona = ángulo",
    nivel: "principiante", tipo: ["sentada"], zona: ["caderas", "ingles", "zona lumbar"],
    dinamica: ["apertura de cadera", "flexión hacia adelante"], tema: ["soltar", "calma"], img: null,
    entrada: [
      "Sentada, junta las plantas de los pies y deja caer las rodillas a los lados.",
      "Acerca los talones a las ingles lo que permita la cadera; isquiones firmes en el suelo.",
      "Alarga la columna hacia arriba; si quieres más, inclínate desde la cadera sin redondear.",
    ],
    precaucion: ["Lesión de ingle o de rodilla: pon soportes bajo los muslos."],
  },
  {
    slug: "ustrasana", apiId: 6, fuente: "yoga-api",
    es: "Postura del camello", en: "Camel", san: "Ustrasana", trad: "ustra = camello",
    nivel: "intermedio", tipo: ["arrodillada"], zona: ["columna", "pecho", "cuádriceps", "psoas", "hombros"],
    dinamica: ["extensión de columna"], tema: ["expansión", "corazón", "confianza"],
    img: "Ustrasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "De rodillas, al ancho de la cadera, tibias y empeines firmes en el suelo.",
      "Lleva la pelvis ligeramente adelante y sube las costillas antes de arquear.",
      "Manos a los talones o a bloques; abre el pecho al techo, cuello largo (no lo dejes caer de golpe).",
    ],
    precaucion: ["Presión arterial alta o baja, migraña, lesión lumbar o de cuello."],
  },
  {
    slug: "marjaryasana", apiId: 7, fuente: "yoga-api",
    es: "Postura del gato", en: "Cat", san: "Marjaryasana", trad: "marjara = gato",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["columna", "cuello", "core"],
    dinamica: ["flexión hacia adelante", "extensión de columna"], tema: ["calma", "soltar"], img: null,
    entrada: [
      "En cuadrupedia, muñecas bajo los hombros y rodillas bajo la cadera.",
      "Al exhalar, redondea la columna hacia el techo y separa los omóplatos.",
      "Deja caer la coronilla; la mirada hacia el ombligo. Se alterna con la vaca al ritmo de la respiración.",
    ],
    precaucion: ["Lesión de muñeca: apoya los antebrazos o cierra los puños."],
  },
  {
    slug: "bitilasana", apiId: 8, fuente: "yoga-api",
    es: "Postura de la vaca", en: "Cow", san: "Bitilasana", trad: "bitila = vaca",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["columna", "pecho", "cuello"],
    dinamica: ["extensión de columna"], tema: ["expansión", "energía"], img: null,
    entrada: [
      "En cuadrupedia, muñecas bajo los hombros y rodillas bajo la cadera.",
      "Al inhalar, lleva el esternón y los isquiones hacia arriba con una curva suave en la lumbar.",
      "Hombros lejos de las orejas; mirada al frente o ligeramente arriba.",
    ],
    precaucion: ["Molestia de cuello: mantén la mirada al frente en vez de subir la barbilla."],
  },
  {
    slug: "utkatasana", apiId: 9, fuente: "yoga-api",
    es: "Postura de la silla", en: "Chair", san: "Utkatasana", trad: "utkata = feroz, intensa",
    nivel: "principiante", tipo: ["de pie"], zona: ["cuádriceps", "glúteos", "tobillos y pies", "columna", "hombros"],
    dinamica: ["fuerza"], tema: ["energía", "confianza", "enraizar"],
    img: "Utkatasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Pies juntos o al ancho de la cadera; el peso en los talones.",
      "Dobla las rodillas y lleva los isquiones atrás como para sentarte; costillas sin abrirse.",
      "Sube los brazos junto a las orejas; nuca larga, mirada al frente.",
    ],
    precaucion: ["Lesión de rodilla, presión arterial baja, dolor de cabeza."],
  },
  {
    slug: "balasana", apiId: 10, fuente: "yoga-api",
    es: "Postura del niño", en: "Child's Pose", san: "Balasana", trad: "bala = niño",
    nivel: "principiante", tipo: ["arrodillada", "restaurativa"], zona: ["caderas", "cuádriceps", "columna", "tobillos y pies"],
    dinamica: ["flexión hacia adelante", "quietud"], tema: ["calma", "soltar", "enraizar"], img: null,
    entrada: [
      "De rodillas, junta los dedos gordos de los pies y abre las rodillas al ancho que necesites.",
      "Lleva los glúteos hacia los talones y la frente al suelo o a un bloque.",
      "Brazos estirados adelante o a los lados del cuerpo; respiración hacia la espalda.",
    ],
    precaucion: ["Lesión de rodilla, embarazo avanzado (abre bien las rodillas), diarrea."],
  },
  {
    slug: "savasana", apiId: 11, fuente: "yoga-api+propia",
    es: "Postura del cadáver", en: "Corpse", san: "Savasana", trad: "sava = cadáver",
    nivel: "principiante", tipo: ["supina", "restaurativa"], zona: ["columna"],
    dinamica: ["quietud"], tema: ["calma", "soltar"], img: null,
    entrada: [
      "Boca arriba, piernas separadas al ancho del tapete, pies cayendo hacia afuera.",
      "Brazos ligeramente separados del cuerpo, palmas hacia arriba, hombros apoyados.",
      "Cierra los ojos y suelta el peso del cuerpo; respiración natural. 5–10 min al cierre de la clase.",
    ],
    beneficios: [
      "Calma el sistema nervioso y baja la activación del estrés.",
      "Reduce fatiga, dolor de cabeza e insomnio.",
      "Integra el trabajo de toda la práctica.",
    ],
    precaucion: ["Embarazo: túmbate de lado o con el torso elevado. Lumbalgia: dobla las rodillas o pon un bolster bajo ellas."],
  },
  {
    slug: "alanasana", apiId: 12, fuente: "yoga-api+propia",
    es: "Zancada alta / luna creciente", en: "Crescent Lunge", san: "Ashta Chandrasana", trad: "ashta chandra = media luna",
    nivel: "intermedio", tipo: ["de pie"], zona: ["psoas", "cuádriceps", "ingles", "pecho"],
    dinamica: ["apertura de cadera", "equilibrio", "extensión de columna"], tema: ["expansión", "energía", "confianza"], img: null,
    entrada: [
      "Desde perro boca abajo, lleva un pie entre las manos; el talón de atrás sube (zancada sobre la punta).",
      "Rodilla delantera sobre el tobillo; lleva la pelvis un poco hacia adelante para alargar el psoas de atrás.",
      "Sube los brazos junto a las orejas; costillas cerradas, mirada al frente.",
    ],
    beneficios: [
      "Estira psoas, ingles y cuádriceps de la pierna de atrás.",
      "Fortalece piernas y glúteos.",
      "Abre el pecho y trabaja el equilibrio.",
    ],
    precaucion: ["Lesión de rodilla: baja la rodilla de atrás al suelo (zancada baja)."],
  },
  {
    slug: "bakasana", apiId: 13, fuente: "yoga-api",
    es: "Postura del cuervo", en: "Crow", san: "Bakasana", trad: "baka = grulla",
    nivel: "intermedio", tipo: ["equilibrio de brazos"], zona: ["muñecas", "core", "hombros"],
    dinamica: ["fuerza", "equilibrio"], tema: ["confianza", "foco"],
    img: "Bakasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "En cuclillas, manos al suelo al ancho de los hombros, dedos bien abiertos.",
      "Apoya las rodillas en la parte alta de los brazos y lleva el peso adelante hasta que los pies floten.",
      "Redondea la espalda alta, mira ligeramente adelante (no al suelo entre las manos).",
    ],
    precaucion: ["Síndrome del túnel carpiano, lesión de muñeca o de hombro, embarazo."],
  },
  {
    slug: "ardha-pincha-mayurasana", apiId: 14, fuente: "yoga-api",
    es: "Postura del delfín", en: "Dolphin", san: "Ardha Pincha Mayurasana", trad: "pincha = pluma, mayura = pavo real",
    nivel: "intermedio", tipo: ["invertida"], zona: ["hombros", "isquiotibiales", "core"],
    dinamica: ["fuerza", "flexión hacia adelante"], tema: ["foco", "energía"], img: null,
    entrada: [
      "Desde cuadrupedia, apoya los antebrazos paralelos, codos al ancho de los hombros.",
      "Estira las piernas y lleva los isquiones hacia arriba y atrás, como en perro boca abajo.",
      "Empuja el suelo con los antebrazos; orejas lejos de los hombros, mirada a los pies.",
    ],
    precaucion: ["Lesión de hombro o de cuello."],
  },
  {
    slug: "adho-mukha-svanasana", apiId: 15, fuente: "yoga-api+propia",
    es: "Perro boca abajo", en: "Downward-Facing Dog", san: "Adho Mukha Svanasana", trad: "adho = abajo, mukha = cara, svana = perro",
    nivel: "principiante", tipo: ["invertida", "de pie"], zona: ["hombros", "isquiotibiales", "core", "tobillos y pies"],
    dinamica: ["flexión hacia adelante", "fuerza"], tema: ["enraizar", "calma"], img: null,
    entrada: [
      "Desde cuadrupedia, manos un palmo delante de los hombros, dedos abiertos.",
      "Lleva los isquiones arriba y atrás formando una V invertida; piernas activas, rodillas pueden ir dobladas.",
      "Empuja el suelo con las manos, orejas lejos de los hombros; talones hacia el suelo sin forzar.",
    ],
    beneficios: [
      "Estira isquiotibiales, gemelos, hombros y manos.",
      "Fortalece brazos y piernas.",
      "Calma la mente y da energía a la vez; alivia dolor de espalda y fatiga.",
    ],
    precaucion: ["Túnel carpiano, lesión de hombro, presión arterial alta, últimas semanas de embarazo."],
  },
  {
    slug: "garudasana", apiId: 16, fuente: "yoga-api",
    es: "Postura del águila", en: "Eagle", san: "Garudasana", trad: "garuda = águila",
    nivel: "intermedio", tipo: ["de pie", "equilibrio"], zona: ["hombros", "caderas", "tobillos y pies"],
    dinamica: ["equilibrio", "apertura de cadera"], tema: ["foco", "enraizar"],
    img: "Garudasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "De pie, dobla las rodillas y cruza un muslo sobre el otro; el pie engancha detrás de la pantorrilla si llega.",
      "Cruza los brazos, un codo dentro del otro, y junta las palmas; sube los codos a la altura de los hombros.",
      "Isquiones abajo, mirada a un punto fijo. Repite del otro lado.",
    ],
    precaucion: ["Lesión de rodilla o de tobillo."],
  },
  {
    slug: "utthita-hasta-padangusthasana", apiId: 17, fuente: "yoga-api",
    es: "Mano al dedo gordo de pie", en: "Extended Hand to Big Toe", san: "Utthita Hasta Padangusthasana", trad: "hasta = mano, padangustha = dedo gordo",
    nivel: "avanzado", tipo: ["de pie", "equilibrio"], zona: ["isquiotibiales", "caderas", "core"],
    dinamica: ["equilibrio", "flexión hacia adelante", "apertura de cadera"], tema: ["foco", "confianza"],
    img: "Utthita-Hasta-Padangusthasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "De pie, lleva una rodilla al pecho y toma el dedo gordo con dos dedos (o usa un cinturón).",
      "Estira la pierna al frente lo que permitan los isquiotibiales, sin colapsar el pecho.",
      "Abre la pierna a un lado si hay estabilidad; la cadera queda nivelada. Mirada fija.",
    ],
    precaucion: ["Lesión de isquiotibiales o de tobillo."],
  },
  {
    slug: "utthita-parsvakonasana", apiId: 18, fuente: "yoga-api",
    es: "Ángulo lateral extendido", en: "Extended Side Angle", san: "Utthita Parsvakonasana", trad: "parsva = lado, kona = ángulo",
    nivel: "intermedio", tipo: ["de pie"], zona: ["cuádriceps", "ingles", "columna", "hombros", "pecho"],
    dinamica: ["flexión lateral", "fuerza", "apertura de cadera"], tema: ["expansión", "energía"],
    img: "Utthita-Parshvakonasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Desde guerrero II, apoya el antebrazo en el muslo delantero o la mano en el suelo por dentro del pie.",
      "El brazo de arriba se estira junto a la oreja creando una línea larga del talón de atrás a la mano.",
      "Gira el pecho hacia el techo; el cuello sigue la línea del torso.",
    ],
    precaucion: ["Lesión de rodilla o de cuello, presión arterial alta o baja."],
  },
  {
    slug: "pincha-mayurasana", apiId: 19, fuente: "yoga-api",
    es: "Parada sobre antebrazos", en: "Forearm Stand", san: "Pincha Mayurasana", trad: "pincha = pluma, mayura = pavo real",
    nivel: "avanzado", tipo: ["invertida", "equilibrio de brazos"], zona: ["hombros", "core", "columna"],
    dinamica: ["inversión", "fuerza", "equilibrio"], tema: ["confianza", "foco"], img: null,
    entrada: [
      "Antebrazos paralelos en el suelo, codos al ancho de los hombros; suele hacerse contra la pared.",
      "Lleva los hombros sobre los codos y sube una pierna y luego la otra.",
      "Empuja el suelo con los antebrazos, costillas cerradas, mirada entre las manos.",
    ],
    precaucion: ["Lesión de hombro, cuello o espalda; presión arterial alta; menstruación; embarazo."],
  },
  {
    slug: "uttanasana-hombros", apiId: 20, fuente: "yoga-api",
    es: "Pinza de pie con manos entrelazadas", en: "Forward Bend with Shoulder Opener", san: "Uttanasana (variación)", trad: "uttana = estiramiento intenso",
    nivel: "intermedio", tipo: ["de pie"], zona: ["isquiotibiales", "hombros", "zona lumbar", "cuello"],
    dinamica: ["flexión hacia adelante"], tema: ["soltar", "calma"], img: null,
    entrada: [
      "De pie, entrelaza los dedos detrás de la espalda y estira los brazos.",
      "Inclínate desde la cadera con la columna larga; rodillas un poco dobladas si los isquios están tensos.",
      "Deja caer los brazos por encima de la cabeza hacia el suelo; nuca y cuello sueltos.",
    ],
    precaucion: ["Lesión lumbar (dobla las rodillas), lesión de hombro, presión arterial baja."],
  },
  {
    slug: "ardha-chandrasana", apiId: 21, fuente: "yoga-api",
    es: "Media luna", en: "Half Moon", san: "Ardha Chandrasana", trad: "ardha = media, chandra = luna",
    nivel: "intermedio", tipo: ["de pie", "equilibrio"], zona: ["isquiotibiales", "caderas", "core", "glúteos"],
    dinamica: ["equilibrio", "apertura de cadera", "flexión lateral"], tema: ["expansión", "confianza"],
    img: "Ardha-Chandrasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Desde triángulo o guerrero II, lleva la mano de abajo al suelo un palmo por delante del meñique del pie.",
      "Eleva la pierna de atrás paralela al suelo, pie flex; abre la cadera de arriba hacia el techo.",
      "El brazo de arriba sube en línea con el de abajo; mirada al frente o a la mano (según el cuello).",
    ],
    precaucion: ["Lesión de rodilla o tobillo, migraña, presión arterial baja, diarrea."],
  },
  {
    slug: "adho-mukha-vrksasana", apiId: 22, fuente: "yoga-api",
    es: "Parada de manos", en: "Handstand", san: "Adho Mukha Vrksasana", trad: "adho mukha = cara abajo, vrksa = árbol",
    nivel: "avanzado", tipo: ["invertida", "equilibrio de brazos"], zona: ["hombros", "muñecas", "core"],
    dinamica: ["inversión", "fuerza", "equilibrio"], tema: ["confianza", "foco", "energía"], img: null,
    entrada: [
      "Manos al ancho de los hombros, dedos abiertos; suele hacerse contra la pared.",
      "Lleva los hombros sobre las muñecas y patea una pierna arriba y luego la otra.",
      "Empuja el suelo con brazos rectos, costillas cerradas, pies activos hacia el techo.",
    ],
    precaucion: ["Lesión de hombro, cuello o muñeca; presión arterial alta; menstruación; embarazo."],
  },
  {
    slug: "anjaneyasana", apiId: 23, fuente: "yoga-api",
    es: "Zancada baja", en: "Low Lunge", san: "Anjaneyasana", trad: "Anjaneya = otro nombre de Hanuman",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["psoas", "ingles", "cuádriceps", "pecho"],
    dinamica: ["apertura de cadera", "extensión de columna"], tema: ["expansión", "soltar"], img: null,
    entrada: [
      "Un pie al frente con la rodilla sobre el tobillo; la rodilla de atrás en el suelo, empeine apoyado.",
      "Lleva la pelvis hacia adelante y abajo para alargar el psoas de la pierna de atrás.",
      "Sube los brazos o llévalos a la rodilla delantera; pecho abierto, coxis hacia abajo.",
    ],
    precaucion: ["Molestia de rodilla: pon un cojín bajo la rótula de atrás."],
  },
  {
    slug: "supta-kapotasana", apiId: 24, fuente: "yoga-api",
    es: "Paloma tumbada (ojo de aguja)", en: "Reclined Pigeon", san: "Supta Kapotasana", trad: "supta = tumbado, kapota = paloma",
    nivel: "principiante", tipo: ["supina", "restaurativa"], zona: ["caderas", "glúteos", "zona lumbar"],
    dinamica: ["apertura de cadera", "quietud"], tema: ["soltar", "calma"], img: null,
    entrada: [
      "Boca arriba, rodillas dobladas; cruza un tobillo por encima de la rodilla contraria.",
      "Pasa la mano entre las piernas y entrelaza los dedos detrás del muslo.",
      "Acerca el muslo al pecho manteniendo el sacro en el suelo y los hombros sueltos.",
    ],
    precaucion: ["Lesión de rodilla o de cadera; embarazo (hazla de lado)."],
  },
  {
    slug: "eka-pada-rajakapotasana", apiId: 25, fuente: "yoga-api",
    es: "Paloma real", en: "King Pigeon", san: "Eka Pada Rajakapotasana", trad: "eka pada = una pierna, raja = rey, kapota = paloma",
    nivel: "intermedio", tipo: ["sentada"], zona: ["caderas", "glúteos", "psoas", "cuádriceps", "pecho"],
    dinamica: ["apertura de cadera", "extensión de columna"], tema: ["soltar", "corazón"],
    img: "Eka-Pada-Raja-Kapotasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Desde perro boca abajo, lleva una espinilla hacia adelante; la pierna de atrás estirada, empeine abajo.",
      "Nivela la cadera (peso repartido); si el glúteo no llega al suelo, pon un soporte debajo.",
      "Torso erguido para abrir cadera, o inclínate hacia adelante para soltar. Repite del otro lado.",
    ],
    precaucion: ["Lesión de rodilla, tobillo, sacro o lumbar."],
  },
  {
    slug: "phalakasana", apiId: 26, fuente: "yoga-api",
    es: "Plancha", en: "Plank", san: "Phalakasana", trad: "phalaka = tabla",
    nivel: "principiante", tipo: ["equilibrio de brazos"], zona: ["core", "hombros", "muñecas"],
    dinamica: ["fuerza"], tema: ["energía", "foco"],
    img: "Chaturanga-Dandasana high Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Muñecas bajo los hombros, cuerpo en una línea de la coronilla a los talones.",
      "Empuja el suelo separando los omóplatos; abdomen adentro, coxis hacia los talones.",
      "Nuca larga, mirada un palmo por delante de las manos.",
    ],
    precaucion: ["Túnel carpiano o lesión de muñeca: baja a los antebrazos."],
  },
  {
    slug: "halasana", apiId: 27, fuente: "yoga-api",
    es: "Postura del arado", en: "Plow", san: "Halasana", trad: "hala = arado",
    nivel: "intermedio", tipo: ["invertida"], zona: ["columna", "hombros", "cuello", "isquiotibiales"],
    dinamica: ["inversión", "flexión hacia adelante"], tema: ["calma", "soltar"], img: null,
    entrada: [
      "Desde tumbada, lleva las piernas por encima de la cabeza hasta que los pies toquen el suelo detrás.",
      "Sostén la espalda con las manos o entrelaza los dedos en el suelo; torso perpendicular al piso.",
      "Nuca larga, sin girar la cabeza en ningún momento. Mirada al pecho.",
    ],
    precaucion: ["Lesión de cuello, presión arterial alta, menstruación, embarazo, glaucoma."],
  },
  {
    slug: "parsvottanasana", apiId: 28, fuente: "yoga-api",
    es: "Estiramiento lateral intenso (pirámide)", en: "Pyramid", san: "Parsvottanasana", trad: "parsva = lado, uttana = estiramiento intenso",
    nivel: "intermedio", tipo: ["de pie"], zona: ["isquiotibiales", "caderas", "columna", "hombros"],
    dinamica: ["flexión hacia adelante"], tema: ["calma", "foco"], img: null,
    entrada: [
      "Un pie al frente y otro atrás (zancada corta), las dos caderas apuntando al frente.",
      "Inclínate desde la cadera con la columna larga; manos al suelo o a bloques a los lados del pie.",
      "Lleva el peso a la pierna de atrás; acerca el vientre al muslo sin redondear.",
    ],
    precaucion: ["Lesión lumbar o de isquiotibiales, presión arterial alta."],
  },
  {
    slug: "parsva-virabhadrasana", apiId: 29, fuente: "yoga-api",
    es: "Guerrero invertido", en: "Reverse Warrior", san: "Viparita Virabhadrasana", trad: "viparita = invertido, virabhadra = guerrero",
    nivel: "principiante", tipo: ["de pie"], zona: ["cuádriceps", "ingles", "columna", "hombros"],
    dinamica: ["flexión lateral", "fuerza"], tema: ["expansión", "energía"], img: null,
    entrada: [
      "Desde guerrero II, gira la palma delantera hacia el techo y sube ese brazo junto a la oreja.",
      "La mano de atrás baja por el muslo de atrás (no apoyes peso en la rodilla).",
      "Alarga el costado de arriba en vez de arquear la lumbar; rodilla delantera sigue doblada.",
    ],
    precaucion: ["Lesión de rodilla o de cuello."],
  },
  {
    slug: "paschimottanasana", apiId: 30, fuente: "yoga-api",
    es: "Pinza sentada", en: "Seated Forward Bend", san: "Paschimottanasana", trad: "paschima = oeste (espalda), uttana = estiramiento intenso",
    nivel: "principiante", tipo: ["sentada"], zona: ["isquiotibiales", "columna", "zona lumbar", "hombros"],
    dinamica: ["flexión hacia adelante"], tema: ["calma", "soltar", "foco"],
    img: "Paschimotanasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Sentada con las piernas al frente; si la lumbar se redondea, siéntate sobre una manta o dobla las rodillas.",
      "Alarga la columna hacia arriba y luego inclínate desde la cadera, no desde la cintura.",
      "Toma las tibias, los pies o un cinturón; el pecho busca los muslos, la nuca larga.",
    ],
    precaucion: ["Lesión lumbar, hernia de disco, asma, embarazo."],
  },
  {
    slug: "padmasana", apiId: 31, fuente: "yoga-api",
    es: "Postura del loto", en: "Lotus", san: "Padmasana", trad: "padma = loto",
    nivel: "avanzado", tipo: ["sentada"], zona: ["caderas", "ingles", "tobillos y pies"],
    dinamica: ["apertura de cadera", "quietud"], tema: ["calma", "foco", "enraizar"], img: null,
    entrada: [
      "Sentada, lleva un pie sobre el muslo contrario, planta hacia arriba, cerca de la ingle.",
      "Solo si la cadera lo permite sin dolor de rodilla, cruza el segundo pie sobre el otro muslo.",
      "Columna larga, manos en las rodillas. Alterna la pierna de arriba en otra sesión.",
    ],
    precaucion: ["Lesión de rodilla o de tobillo: quédate en medio loto o postura fácil (Sukhasana)."],
  },
  {
    slug: "ardha-matsyendrasana", apiId: 32, fuente: "yoga-api+propia",
    es: "Media torsión sentada (señor de los peces)", en: "Half Lord of the Fishes", san: "Ardha Matsyendrasana", trad: "matsya = pez, indra = señor",
    nivel: "intermedio", tipo: ["sentada"], zona: ["columna", "caderas", "glúteos", "hombros"],
    dinamica: ["torsión", "apertura de cadera"], tema: ["soltar", "energía"],
    img: "Ardha-Matsyendrasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Sentada, dobla una rodilla con el pie por fuera del muslo contrario; la otra pierna doblada, pie cerca del glúteo.",
      "Inhala y alarga la columna; exhala y gira hacia la rodilla de arriba desde la base de la columna.",
      "El codo hace palanca por fuera de la rodilla; el otro brazo apoya detrás. Mirada por encima del hombro.",
    ],
    beneficios: [
      "Moviliza la columna y estira glúteos y hombros.",
      "Masajea los órganos abdominales y favorece la digestión.",
      "Alterna compresión y espacio a ambos lados de la espalda.",
    ],
    precaucion: ["Lesión lumbar o de columna, hernia de disco, embarazo (torsión abierta)."],
  },
  {
    slug: "salamba-sarvangasana", apiId: 33, fuente: "yoga-api",
    es: "Vela (parada sobre hombros)", en: "Shoulder Stand", san: "Salamba Sarvangasana", trad: "salamba = con apoyo, sarvanga = todo el cuerpo",
    nivel: "intermedio", tipo: ["invertida"], zona: ["hombros", "cuello", "columna", "core"],
    dinamica: ["inversión"], tema: ["calma", "foco"], img: null,
    entrada: [
      "Desde tumbada, con mantas bajo los hombros, sube las piernas y lleva las manos a la espalda.",
      "Acerca los codos entre sí y sube el torso hacia la vertical; peso en los hombros, no en el cuello.",
      "Nuca larga, sin girar la cabeza. Baja vértebra a vértebra para salir.",
    ],
    precaucion: ["Lesión de cuello o de hombro, presión arterial alta, menstruación, embarazo, glaucoma."],
  },
  {
    slug: "vasisthasana", apiId: 34, fuente: "yoga-api",
    es: "Plancha lateral", en: "Side Plank", san: "Vasisthasana", trad: "Vasistha = nombre de un sabio",
    nivel: "intermedio", tipo: ["equilibrio de brazos"], zona: ["core", "hombros", "muñecas", "glúteos"],
    dinamica: ["fuerza", "equilibrio"], tema: ["confianza", "foco"], img: null,
    entrada: [
      "Desde plancha, apoya el peso en una mano y el canto externo de ese pie; apila los pies o escalona.",
      "Empuja el suelo y sube la cadera; el cuerpo forma una línea diagonal.",
      "Sube el brazo libre al techo; mirada al frente o a la mano de arriba.",
    ],
    precaucion: ["Lesión de muñeca, codo u hombro."],
  },
  {
    slug: "salamba-bhujangasana", apiId: 35, fuente: "yoga-api",
    es: "Esfinge", en: "Sphinx", san: "Salamba Bhujangasana", trad: "salamba = apoyada, bhujanga = serpiente",
    nivel: "principiante", tipo: ["prona", "restaurativa"], zona: ["columna", "zona lumbar", "pecho"],
    dinamica: ["extensión de columna", "quietud"], tema: ["expansión", "calma"], img: null,
    entrada: [
      "Boca abajo, antebrazos en el suelo con los codos bajo los hombros.",
      "Empeines y pubis apoyados; al inhalar lleva el esternón adelante y arriba.",
      "Hombros lejos de las orejas; extensión suave y sostenida en la lumbar alta.",
    ],
    precaucion: ["Lesión lumbar aguda, embarazo (boca abajo no)."],
  },
  {
    slug: "hanumanasana", apiId: 36, fuente: "yoga-api",
    es: "Split (postura de Hanuman)", en: "Splits", san: "Hanumanasana", trad: "Hanuman = deidad mono",
    nivel: "avanzado", tipo: ["sentada"], zona: ["isquiotibiales", "psoas", "ingles", "cuádriceps"],
    dinamica: ["apertura de cadera", "flexión hacia adelante"], tema: ["soltar", "confianza"], img: null,
    entrada: [
      "Desde zancada baja, desliza el talón delantero hacia adelante y la rodilla de atrás hacia atrás.",
      "Pon bloques bajo las manos y baja solo hasta donde puedas con la cadera nivelada al frente.",
      "Coxis hacia abajo; sal con control. Repite del otro lado.",
    ],
    precaucion: ["Lesión de isquiotibiales, ingle o psoas. Calienta bien antes."],
  },
  {
    slug: "malasana", apiId: 37, fuente: "yoga-api",
    es: "Postura de la guirnalda (sentadilla)", en: "Garland Pose", san: "Malasana", trad: "mala = guirnalda",
    nivel: "principiante", tipo: ["de pie"], zona: ["caderas", "ingles", "tobillos y pies", "zona lumbar"],
    dinamica: ["apertura de cadera", "flexión hacia adelante"], tema: ["enraizar", "soltar"], img: null,
    entrada: [
      "Pies un poco más anchos que la cadera, puntas ligeramente afuera; baja en cuclillas.",
      "Si los talones no llegan al suelo, apóyalos en una manta enrollada.",
      "Codos por dentro de las rodillas, palmas juntas; alarga el frente del torso.",
    ],
    precaucion: ["Lesión de rodilla, tobillo o lumbar."],
  },
  {
    slug: "uttanasana", apiId: 38, fuente: "yoga-api",
    es: "Pinza de pie", en: "Standing Forward Bend", san: "Uttanasana", trad: "uttana = estiramiento intenso",
    nivel: "principiante", tipo: ["de pie"], zona: ["isquiotibiales", "zona lumbar", "cuello"],
    dinamica: ["flexión hacia adelante"], tema: ["calma", "soltar"], img: null,
    entrada: [
      "De pie, pies al ancho de la cadera; inclínate desde la cadera con la columna larga.",
      "Rodillas un poco dobladas si los isquiotibiales están tensos; manos al suelo, tibias o codos.",
      "Cabeza y cuello pesados y sueltos; el peso ligeramente hacia las puntas de los pies.",
    ],
    precaucion: ["Lesión lumbar (dobla rodillas), presión arterial baja, hernia de disco."],
  },
  {
    slug: "ashta-chandrasana", apiId: 39, fuente: "yoga-api+propia",
    es: "Luna creciente con torsión", en: "Crescent with Twist", san: "Parivrtta Ashta Chandrasana", trad: "parivrtta = girada, ashta chandra = media luna",
    nivel: "intermedio", tipo: ["de pie"], zona: ["columna", "psoas", "cuádriceps", "core"],
    dinamica: ["torsión", "apertura de cadera", "equilibrio"], tema: ["energía", "foco"], img: null,
    entrada: [
      "Desde zancada alta, junta las palmas frente al pecho.",
      "Exhala y gira el torso hacia la pierna delantera; el codo hace palanca por fuera del muslo.",
      "Caderas apuntando al frente; alarga la columna antes de girar más.",
    ],
    beneficios: [
      "Combina torsión con estiramiento de psoas y trabajo de piernas.",
      "Estimula la digestión.",
      "Mejora el equilibrio y la concentración.",
    ],
    precaucion: ["Lesión lumbar o de rodilla, embarazo."],
  },
  {
    slug: "upavistha-konasana", apiId: 40, fuente: "yoga-api",
    es: "Ángulo abierto sentada", en: "Wide-Angle Seated Forward Bend", san: "Upavistha Konasana", trad: "upavistha = sentada, kona = ángulo",
    nivel: "intermedio", tipo: ["sentada"], zona: ["isquiotibiales", "ingles", "caderas", "columna"],
    dinamica: ["apertura de cadera", "flexión hacia adelante"], tema: ["soltar", "calma"], img: null,
    entrada: [
      "Sentada, abre las piernas a una V cómoda; rótulas y puntas de los pies hacia el techo.",
      "Siéntate sobre una manta si la lumbar se redondea; manos detrás de la cadera para alargar.",
      "Camina las manos hacia adelante desde la cadera, columna larga, sin forzar.",
    ],
    precaucion: ["Lesión lumbar o de isquiotibiales."],
  },
  {
    slug: "vrksasana", apiId: 41, fuente: "yoga-api",
    es: "Postura del árbol", en: "Tree", san: "Vrksasana", trad: "vrksa = árbol",
    nivel: "principiante", tipo: ["de pie", "equilibrio"], zona: ["tobillos y pies", "caderas", "core"],
    dinamica: ["equilibrio", "apertura de cadera"], tema: ["enraizar", "foco", "calma"],
    img: "Vriksasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "De pie, lleva la planta de un pie a la pantorrilla o al muslo interno (nunca sobre la rodilla).",
      "Empuja el pie contra la pierna y la pierna contra el pie; abre la rodilla hacia el lado.",
      "Manos al pecho o arriba; mira a un punto fijo. Repite del otro lado.",
    ],
    precaucion: ["Migraña, presión arterial baja, vértigo."],
  },
  {
    slug: "trikonasana", apiId: 42, fuente: "yoga-api",
    es: "Triángulo extendido", en: "Triangle", san: "Utthita Trikonasana", trad: "utthita = extendido, trikona = triángulo",
    nivel: "principiante", tipo: ["de pie"], zona: ["isquiotibiales", "caderas", "columna", "pecho", "hombros"],
    dinamica: ["flexión lateral", "apertura de cadera"], tema: ["expansión", "enraizar"],
    img: "Trikonasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Pies separados ~1 m; talón delantero alineado con el arco del pie trasero.",
      "Alarga los dos costados y luego inclínate desde la cadera, no desde la cintura.",
      "Mano abajo a la espinilla o a un bloque; abre el pecho al techo, brazos en una línea.",
    ],
    precaucion: ["Presión arterial baja, migraña, diarrea, lesión de cuello (mira al suelo)."],
  },
  {
    slug: "urdhva-mukha-svanasana", apiId: 43, fuente: "yoga-api",
    es: "Perro boca arriba", en: "Upward-Facing Dog", san: "Urdhva Mukha Svanasana", trad: "urdhva = arriba, mukha = cara, svana = perro",
    nivel: "intermedio", tipo: ["prona"], zona: ["columna", "pecho", "hombros", "muñecas", "cuádriceps"],
    dinamica: ["extensión de columna", "fuerza"], tema: ["expansión", "energía", "corazón"], img: null,
    entrada: [
      "Boca abajo, manos junto a las costillas bajas, empeines apoyados.",
      "Empuja el suelo y estira los brazos; muslos y rodillas despegan del tapete.",
      "Hombros atrás y abajo, pecho adelante; nuca larga, sin apretar los glúteos en exceso.",
    ],
    precaucion: ["Lesión lumbar, túnel carpiano, embarazo."],
  },
  {
    slug: "virabhadrasana-i", apiId: 44, fuente: "yoga-api",
    es: "Guerrero I", en: "Warrior I", san: "Virabhadrasana I", trad: "Virabhadra = guerrero mítico",
    nivel: "principiante", tipo: ["de pie"], zona: ["cuádriceps", "psoas", "ingles", "hombros", "pecho"],
    dinamica: ["fuerza", "apertura de cadera"], tema: ["confianza", "energía", "enraizar"], img: null,
    entrada: [
      "Zancada larga; el pie de atrás a ~45–60°, talón en el suelo, las dos caderas al frente.",
      "Rodilla delantera sobre el tobillo; coxis hacia abajo para no cargar la lumbar.",
      "Brazos arriba junto a las orejas; costillas cerradas, mirada al frente.",
    ],
    precaucion: ["Lesión de rodilla, cadera u hombro; presión arterial alta; problemas de corazón."],
  },
  {
    slug: "virabhadrasana-ii", apiId: 45, fuente: "yoga-api",
    es: "Guerrero II", en: "Warrior II", san: "Virabhadrasana II", trad: "Virabhadra = guerrero mítico",
    nivel: "principiante", tipo: ["de pie"], zona: ["cuádriceps", "ingles", "hombros", "caderas"],
    dinamica: ["fuerza", "apertura de cadera"], tema: ["confianza", "energía", "enraizar"], img: null,
    entrada: [
      "Zancada amplia; pie delantero al frente, pie de atrás paralelo al borde corto, arcos alineados.",
      "Dobla la rodilla delantera hacia 90° sobre el tobillo; empuja la rodilla hacia el meñique.",
      "Brazos a los lados a la altura de los hombros; torso centrado, mirada sobre la mano delantera.",
    ],
    precaucion: ["Lesión de rodilla, cadera o cuello; diarrea; presión arterial alta."],
  },
  {
    slug: "virabhadrasana-iii", apiId: 46, fuente: "yoga-api",
    es: "Guerrero III", en: "Warrior III", san: "Virabhadrasana III", trad: "Virabhadra = guerrero mítico",
    nivel: "intermedio", tipo: ["de pie", "equilibrio"], zona: ["glúteos", "isquiotibiales", "core", "columna"],
    dinamica: ["equilibrio", "fuerza"], tema: ["foco", "confianza"], img: null,
    entrada: [
      "Desde zancada corta, lleva el peso al pie delantero e inclina el torso hacia adelante.",
      "Eleva la pierna de atrás hasta la horizontal; cadera nivelada (no se abre al lado).",
      "Brazos hacia atrás, junto al cuerpo o al frente; cuerpo en una línea del talón a la coronilla.",
    ],
    precaucion: ["Presión arterial alta, lesión de tobillo."],
  },
  {
    slug: "urdhva-dhanurasana", apiId: 47, fuente: "yoga-api",
    es: "Rueda / puente completo", en: "Wheel", san: "Urdhva Dhanurasana", trad: "urdhva = arriba, dhanur = arco",
    nivel: "avanzado", tipo: ["supina"], zona: ["columna", "hombros", "muñecas", "cuádriceps", "pecho"],
    dinamica: ["extensión de columna", "fuerza"], tema: ["expansión", "energía", "corazón"],
    img: "Chakrasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Boca arriba, pies al ancho de la cadera cerca de los glúteos; manos junto a las orejas, dedos a los pies.",
      "Empuja con manos y pies y sube la pelvis; primero apoya la coronilla, luego estira los brazos.",
      "Muslos hacia adentro, pecho hacia las manos; sal con la barbilla al pecho.",
    ],
    precaucion: ["Túnel carpiano, lesión lumbar o de hombro, presión arterial alta o baja, migraña, embarazo."],
  },
  {
    slug: "camatkarasana", apiId: 48, fuente: "yoga-api",
    es: "Wild thing / la maravilla", en: "Wild Thing", san: "Camatkarasana", trad: "camatkara = asombro, maravilla",
    nivel: "intermedio", tipo: ["equilibrio de brazos"], zona: ["pecho", "hombros", "psoas", "cuádriceps", "columna"],
    dinamica: ["extensión de columna", "apertura de cadera"], tema: ["expansión", "corazón", "energía"], img: null,
    entrada: [
      "Desde perro boca abajo, sube una pierna y apila la cadera de arriba sobre la de abajo.",
      "Baja el pie de arriba por detrás hacia el suelo, rodilla doblada; el otro pie firme.",
      "Extiende el brazo libre por encima de la cabeza; sube la cadera y abre el pecho.",
    ],
    precaucion: ["Lesión de muñeca, hombro, lumbar o cuello."],
  },

  // ---------- Añadidas a mano (no están en yoga-api) ----------
  {
    slug: "sukhasana", apiId: null, fuente: "propia",
    es: "Postura fácil", en: "Easy Pose", san: "Sukhasana", trad: "sukha = agradable, cómodo",
    nivel: "principiante", tipo: ["sentada"], zona: ["caderas", "columna"],
    dinamica: ["apertura de cadera", "quietud"], tema: ["calma", "enraizar", "foco"], img: null,
    entrada: [
      "Sentada con las piernas cruzadas por las espinillas; siéntate sobre una manta para elevar la cadera.",
      "Rodillas por debajo de la altura de la cadera; isquiones firmes y parejos.",
      "Columna larga sin rigidez, hombros sueltos, manos en los muslos. Alterna el cruce.",
    ],
    beneficios: [
      "Base cómoda para respiración y meditación.",
      "Abre suavemente las caderas y alarga la columna.",
      "Calma el sistema nervioso.",
    ],
    precaucion: ["Molestia de rodilla o cadera: eleva más el asiento o siéntate en una silla."],
  },
  {
    slug: "vajrasana", apiId: null, fuente: "propia",
    es: "Postura del rayo (sentada sobre los talones)", en: "Thunderbolt Pose", san: "Vajrasana", trad: "vajra = rayo, diamante",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["cuádriceps", "tobillos y pies", "columna"],
    dinamica: ["quietud"], tema: ["calma", "enraizar", "foco"], img: null,
    entrada: [
      "De rodillas, junta las piernas y siéntate sobre los talones; empeines apoyados.",
      "Si molesta, pon un cojín entre glúteos y talones o una manta bajo los tobillos.",
      "Columna larga, manos en los muslos, mirada al frente o los ojos cerrados.",
    ],
    beneficios: [
      "Favorece la digestión (una de las pocas posturas que se pueden hacer tras comer).",
      "Alarga la columna y aquieta la mente.",
      "Estira empeines y tobillos.",
    ],
    precaucion: ["Lesión de rodilla o de tobillo."],
  },
  {
    slug: "gomukhasana", apiId: null, fuente: "propia",
    es: "Cara de vaca", en: "Cow Face Pose", san: "Gomukhasana", trad: "go = vaca, mukha = cara",
    nivel: "intermedio", tipo: ["sentada"], zona: ["caderas", "glúteos", "hombros", "pecho"],
    dinamica: ["apertura de cadera"], tema: ["soltar", "expansión"],
    img: "Gomukhasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Sentada, cruza una rodilla sobre la otra apilándolas al centro; pies junto a cada cadera.",
      "Siéntate sobre una manta si la cadera lo pide; isquiones parejos.",
      "Sube un brazo y dóblalo detrás de la cabeza, el otro sube por la espalda; engancha los dedos o usa un cinturón.",
    ],
    beneficios: [
      "Abre caderas, glúteos y parte externa del muslo.",
      "Estira hombros, tríceps y pecho.",
      "Contrarresta la postura de estar mucho tiempo sentada.",
    ],
    precaucion: ["Lesión de hombro o de rodilla: trabaja solo la parte baja o solo la alta."],
  },
  {
    slug: "janu-sirsasana", apiId: null, fuente: "propia",
    es: "Cabeza a la rodilla", en: "Head-to-Knee Pose", san: "Janu Sirsasana", trad: "janu = rodilla, sirsa = cabeza",
    nivel: "principiante", tipo: ["sentada"], zona: ["isquiotibiales", "zona lumbar", "caderas", "columna"],
    dinamica: ["flexión hacia adelante", "apertura de cadera"], tema: ["calma", "soltar"],
    img: "Janusirsasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Sentada, una pierna al frente y la otra doblada con la planta en el muslo interno.",
      "Gira el torso hacia la pierna estirada; alarga la columna y luego inclínate desde la cadera.",
      "Toma el pie o un cinturón; siéntate sobre una manta si la lumbar se redondea. Repite del otro lado.",
    ],
    beneficios: [
      "Estira isquiotibiales, ingle y columna de un lado a la vez.",
      "Calma la mente y alivia la ansiedad ligera.",
      "Estimula hígado y riñones.",
    ],
    precaucion: ["Lesión lumbar o de rodilla (pon soporte bajo la rodilla doblada)."],
  },
  {
    slug: "supta-baddha-konasana", apiId: null, fuente: "propia",
    es: "Zapatero tumbada", en: "Reclining Bound Angle", san: "Supta Baddha Konasana", trad: "supta = tumbada, baddha kona = ángulo atado",
    nivel: "principiante", tipo: ["supina", "restaurativa"], zona: ["caderas", "ingles", "pecho"],
    dinamica: ["apertura de cadera", "quietud"], tema: ["calma", "soltar", "corazón"], img: null,
    entrada: [
      "Boca arriba (mejor sobre un bolster a lo largo de la columna), junta las plantas de los pies.",
      "Deja caer las rodillas a los lados; pon bloques o cojines bajo los muslos para soltar del todo.",
      "Brazos a los lados, palmas arriba; quédate 3–10 min respirando lento.",
    ],
    beneficios: [
      "Abre caderas e ingles sin esfuerzo.",
      "Relaja el pecho y el vientre; buena para regla y menopausia.",
      "Activa la respuesta de calma del sistema nervioso.",
    ],
    precaucion: ["Lesión de ingle o de rodilla: sube los soportes bajo los muslos. Molestia lumbar o sacra."],
  },
  {
    slug: "ananda-balasana", apiId: null, fuente: "propia",
    es: "Bebé feliz", en: "Happy Baby", san: "Ananda Balasana", trad: "ananda = dicha, bala = bebé",
    nivel: "principiante", tipo: ["supina"], zona: ["caderas", "ingles", "zona lumbar", "isquiotibiales"],
    dinamica: ["apertura de cadera"], tema: ["soltar", "calma"], img: null,
    entrada: [
      "Boca arriba, lleva las rodillas al pecho y toma los bordes externos de los pies (o las corvas).",
      "Abre las rodillas hacia las axilas; tibias perpendiculares al suelo, tobillos sobre las rodillas.",
      "Sacro y nuca en el suelo; puedes mecerte suave lado a lado.",
    ],
    beneficios: [
      "Suelta caderas, ingles y zona lumbar.",
      "Estira suavemente los isquiotibiales.",
      "Calma y descarga tensión tras posturas intensas.",
    ],
    precaucion: ["Embarazo, lesión de cuello o de rodilla."],
  },
  {
    slug: "viparita-karani", apiId: null, fuente: "propia",
    es: "Piernas arriba en la pared", en: "Legs Up the Wall", san: "Viparita Karani", trad: "viparita = invertido, karani = acción",
    nivel: "principiante", tipo: ["invertida", "restaurativa"], zona: ["isquiotibiales", "zona lumbar", "tobillos y pies"],
    dinamica: ["inversión", "quietud"], tema: ["calma", "soltar"],
    img: "Viparita-Karani Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Siéntate de lado pegada a la pared y gira para subir las piernas por ella; glúteos cerca o sobre un cojín.",
      "Brazos a los lados, palmas arriba; hombros y cabeza en el suelo.",
      "Quédate 5–15 min con respiración lenta. Para salir, dobla las rodillas y rueda de lado.",
    ],
    beneficios: [
      "Descarga piernas cansadas y ligera hinchazón de tobillos.",
      "Baja la activación del estrés y ayuda a dormir.",
      "Alivio suave de la zona lumbar.",
    ],
    precaucion: ["Glaucoma, presión arterial alta no controlada, menstruación (opcional), embarazo avanzado."],
  },
  {
    slug: "prasarita-padottanasana", apiId: null, fuente: "propia",
    es: "Flexión de pie con piernas separadas", en: "Wide-Legged Forward Fold", san: "Prasarita Padottanasana", trad: "prasarita = extendido, pada = pie, uttana = estiramiento intenso",
    nivel: "principiante", tipo: ["de pie"], zona: ["isquiotibiales", "caderas", "zona lumbar", "columna"],
    dinamica: ["flexión hacia adelante", "apertura de cadera"], tema: ["calma", "soltar"], img: null,
    entrada: [
      "Pies paralelos, separados ~1,2 m, bordes externos hacia adelante.",
      "Manos a la cadera, alarga la columna y baja desde la cadera con la espalda larga.",
      "Manos al suelo o a bloques bajo los hombros; corona hacia el suelo, peso ligeramente adelante.",
    ],
    beneficios: [
      "Estira isquiotibiales y parte interna de las piernas.",
      "Alarga y descarga la columna; efecto calmante (cabeza abajo).",
      "Fortalece pies y tobillos.",
    ],
    precaucion: ["Lesión lumbar (mantén el torso más alto), presión arterial baja."],
  },
  {
    slug: "ardha-uttanasana", apiId: null, fuente: "propia",
    es: "Media pinza de pie (espalda plana)", en: "Half Standing Forward Bend", san: "Ardha Uttanasana", trad: "ardha = media, uttana = estiramiento intenso",
    nivel: "principiante", tipo: ["de pie"], zona: ["isquiotibiales", "columna", "zona lumbar"],
    dinamica: ["flexión hacia adelante"], tema: ["foco"], img: null,
    entrada: [
      "Desde pinza de pie, lleva las manos a las espinillas o a bloques.",
      "Estira la columna hasta que la espalda quede plana y el pecho se alargue hacia adelante.",
      "Nuca en línea con la columna, mirada al suelo. Transición clave en los saludos al sol.",
    ],
    beneficios: [
      "Enseña a alargar la columna en las flexiones hacia adelante.",
      "Activa la espalda y los isquiotibiales.",
      "Prepara y descomprime entre posturas de pie.",
    ],
    precaucion: ["Lesión lumbar: dobla más las rodillas y sube las manos a bloques altos."],
  },
  {
    slug: "uttana-shishosana", apiId: null, fuente: "propia",
    es: "Postura del cachorro", en: "Puppy Pose / Melting Heart", san: "Uttana Shishosana", trad: "uttana = estiramiento, shishu = cachorro",
    nivel: "principiante", tipo: ["arrodillada", "restaurativa"], zona: ["hombros", "pecho", "columna"],
    dinamica: ["extensión de columna", "quietud"], tema: ["corazón", "soltar", "expansión"], img: null,
    entrada: [
      "Desde cuadrupedia, camina las manos hacia adelante y baja el pecho hacia el suelo.",
      "Caderas sobre las rodillas; frente o barbilla al suelo, axilas hacia el piso.",
      "Brazos activos; extensión suave en la columna alta. Quédate varias respiraciones.",
    ],
    beneficios: [
      "Abre hombros, pecho y dorsales.",
      "Extensión suave de la columna sin cargar la lumbar.",
      "Calma y afloja la parte alta de la espalda.",
    ],
    precaucion: ["Lesión de hombro o de rodilla."],
  },
  {
    slug: "salabhasana", apiId: null, fuente: "propia",
    es: "Postura del saltamontes (langosta)", en: "Locust Pose", san: "Salabhasana", trad: "salabha = saltamontes",
    nivel: "principiante", tipo: ["prona"], zona: ["zona lumbar", "glúteos", "columna", "isquiotibiales", "hombros"],
    dinamica: ["extensión de columna", "fuerza"], tema: ["energía", "confianza"],
    img: "Salabhasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Boca abajo, brazos a los lados del cuerpo, palmas abajo, frente en el suelo.",
      "Al inhalar, despega pecho, brazos y piernas; alarga en vez de subir mucho.",
      "Cuello largo en línea con la columna; empeines activos hacia atrás.",
    ],
    beneficios: [
      "Fortalece toda la cadena posterior: lumbar, glúteos e isquiotibiales.",
      "Mejora la postura y contrarresta el encorvamiento.",
      "Buena preparación para extensiones más profundas.",
    ],
    precaucion: ["Lesión lumbar aguda, embarazo, cirugía abdominal reciente."],
  },
  {
    slug: "matsyasana", apiId: null, fuente: "propia",
    es: "Postura del pez", en: "Fish Pose", san: "Matsyasana", trad: "matsya = pez",
    nivel: "intermedio", tipo: ["supina"], zona: ["pecho", "cuello", "columna", "psoas"],
    dinamica: ["extensión de columna"], tema: ["expansión", "corazón"],
    img: "Matsyasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Boca arriba, manos bajo los glúteos, palmas al suelo, codos hacia adentro.",
      "Apoya en los antebrazos y sube el pecho; lleva la coronilla suavemente al suelo con poco peso.",
      "Piernas activas; el peso vive en los antebrazos y la pelvis, no en la cabeza. Contrapostura de la vela.",
    ],
    beneficios: [
      "Abre pecho, garganta y flexores de la cadera.",
      "Contrarresta la flexión de hombros de la vida diaria.",
      "Estimula la respiración amplia.",
    ],
    precaucion: ["Lesión de cuello o de lumbar, migraña, presión arterial alta o baja."],
  },
  {
    slug: "makarasana", apiId: null, fuente: "propia",
    es: "Postura del cocodrilo", en: "Crocodile Pose", san: "Makarasana", trad: "makara = cocodrilo",
    nivel: "principiante", tipo: ["prona", "restaurativa"], zona: ["zona lumbar", "columna", "hombros"],
    dinamica: ["quietud"], tema: ["calma", "soltar"], img: null,
    entrada: [
      "Boca abajo, apila los antebrazos y apoya la frente sobre ellos.",
      "Piernas separadas y relajadas, talones cayendo hacia afuera.",
      "Siente la respiración expandir la parte baja de la espalda. Descanso entre extensiones.",
    ],
    beneficios: [
      "Suelta la zona lumbar y los hombros.",
      "Enseña respiración diafragmática al sentirla contra el suelo.",
      "Descanso activo entre posturas boca abajo.",
    ],
    precaucion: ["Embarazo (boca abajo no)."],
  },
  {
    slug: "skandasana", apiId: null, fuente: "propia",
    es: "Zancada lateral", en: "Side Lunge", san: "Skandasana", trad: "Skanda = deidad de la guerra",
    nivel: "intermedio", tipo: ["de pie"], zona: ["ingles", "isquiotibiales", "caderas", "tobillos y pies"],
    dinamica: ["apertura de cadera", "flexión hacia adelante"], tema: ["soltar", "enraizar"], img: null,
    entrada: [
      "Desde piernas muy separadas, dobla una rodilla y baja la cadera hacia ese lado.",
      "La otra pierna estirada, punta del pie al techo o apoyada en el canto del talón.",
      "Manos al suelo o al pecho; pecho abierto. Pasa de un lado al otro con fluidez.",
    ],
    beneficios: [
      "Abre ingles y parte interna de las piernas.",
      "Estira un isquiotibial a la vez con la cadera flexionada.",
      "Trabaja movilidad de tobillo y equilibrio.",
    ],
    precaucion: ["Lesión de rodilla, ingle o tobillo."],
  },
  {
    slug: "parighasana", apiId: null, fuente: "propia",
    es: "Postura del cerrojo", en: "Gate Pose", san: "Parighasana", trad: "parigha = barra que cierra una puerta",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["columna", "ingles", "isquiotibiales", "hombros"],
    dinamica: ["flexión lateral", "apertura de cadera"], tema: ["expansión", "soltar"], img: null,
    entrada: [
      "De rodillas, estira una pierna al lado con la planta o el canto del pie en el suelo.",
      "Sube el brazo del lado de la rodilla apoyada; la otra mano baja por la pierna estirada.",
      "Alarga el costado de arriba y gira ligeramente el pecho al techo. Repite del otro lado.",
    ],
    beneficios: [
      "Estira los costados, entre las costillas y los oblicuos.",
      "Abre isquiotibiales e ingle de la pierna estirada.",
      "Mejora la respiración lateral.",
    ],
    precaucion: ["Lesión de rodilla (pon un cojín bajo la rodilla apoyada)."],
  },
  {
    slug: "parivrtta-trikonasana", apiId: null, fuente: "propia",
    es: "Triángulo con torsión", en: "Revolved Triangle", san: "Parivrtta Trikonasana", trad: "parivrtta = girado, trikona = triángulo",
    nivel: "intermedio", tipo: ["de pie"], zona: ["columna", "isquiotibiales", "caderas", "hombros"],
    dinamica: ["torsión", "flexión hacia adelante"], tema: ["foco", "energía"],
    img: "Parivrtta-Trikonasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Zancada corta, las dos caderas al frente; mano contraria a la pierna delantera al suelo o a un bloque por fuera del pie.",
      "Alarga la columna y gira el torso hacia la pierna delantera; el otro brazo sube al techo.",
      "Cuida que la cadera de atrás no se desplome hacia el lado; nuca en línea con la columna.",
    ],
    beneficios: [
      "Torsión profunda con estiramiento de isquiotibiales.",
      "Estimula la digestión y moviliza la columna.",
      "Mejora el equilibrio y la concentración.",
    ],
    precaucion: ["Lesión lumbar o de columna, migraña, presión arterial baja, diarrea, embarazo."],
  },
  {
    slug: "natarajasana", apiId: null, fuente: "propia",
    es: "Postura del bailarín", en: "Dancer Pose", san: "Natarajasana", trad: "nata = bailarín, raja = rey (Shiva Nataraja)",
    nivel: "avanzado", tipo: ["de pie", "equilibrio"], zona: ["cuádriceps", "psoas", "pecho", "hombros", "columna"],
    dinamica: ["equilibrio", "extensión de columna", "apertura de cadera"], tema: ["confianza", "expansión", "foco"],
    img: "Natarajasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "De pie, toma un tobillo por dentro o por fuera; rodillas juntas al inicio.",
      "Lleva el pie hacia atrás y arriba mientras el pecho y el otro brazo se alargan hacia adelante.",
      "Empuja el pie contra la mano para subir; mira a un punto fijo. Repite del otro lado.",
    ],
    beneficios: [
      "Estira cuádriceps, psoas, pecho y hombros.",
      "Fortalece la pierna de apoyo y el equilibrio.",
      "Extensión de columna dinámica con foco mental.",
    ],
    precaucion: ["Lesión lumbar, presión arterial baja, vértigo."],
  },
  {
    slug: "bhujangasana", apiId: null, fuente: "propia",
    es: "Postura de la cobra", en: "Cobra Pose", san: "Bhujangasana", trad: "bhujanga = serpiente",
    nivel: "principiante", tipo: ["prona"], zona: ["columna", "zona lumbar", "pecho", "hombros"],
    dinamica: ["extensión de columna"], tema: ["expansión", "energía", "corazón"],
    img: "Bhujangasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Boca abajo, manos bajo los hombros, codos pegados al cuerpo, empeines apoyados.",
      "Empuja poco con las manos y usa la espalda para subir el pecho; hombros lejos de las orejas.",
      "Pubis en el suelo, glúteos suaves; la altura la marca la lumbar sin dolor.",
    ],
    beneficios: [
      "Fortalece y moviliza la columna.",
      "Abre pecho y hombros; mejora la respiración.",
      "Contrarresta horas de estar encorvada.",
    ],
    precaucion: ["Lesión lumbar aguda, túnel carpiano, embarazo, cirugía abdominal reciente."],
  },
  {
    slug: "virasana", apiId: null, fuente: "propia",
    es: "Postura del héroe", en: "Hero Pose", san: "Virasana", trad: "vira = héroe",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["cuádriceps", "tobillos y pies", "columna"],
    dinamica: ["quietud", "apertura de cadera"], tema: ["calma", "foco", "enraizar"],
    img: "Virasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "De rodillas, separa los pies un poco más que la cadera y siéntate entre los talones.",
      "Si los glúteos no llegan al suelo sin molestia, siéntate sobre un bloque o cojín.",
      "Empeines apoyados y rectos; columna larga, manos en los muslos.",
    ],
    beneficios: [
      "Estira cuádriceps, rodillas y empeines.",
      "Asiento alternativo para respiración y meditación.",
      "Favorece la digestión.",
    ],
    precaucion: ["Lesión de rodilla o de tobillo: eleva bien el asiento o evita."],
  },
  {
    slug: "supta-virasana", apiId: null, fuente: "propia",
    es: "Héroe reclinado", en: "Reclining Hero", san: "Supta Virasana", trad: "supta = reclinado, vira = héroe",
    nivel: "intermedio", tipo: ["arrodillada", "restaurativa"], zona: ["cuádriceps", "psoas", "pecho", "tobillos y pies"],
    dinamica: ["extensión de columna", "apertura de cadera", "quietud"], tema: ["expansión", "soltar"],
    img: "Supta-Virasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Desde postura del héroe, recuéstate hacia atrás sobre los codos y luego sobre un bolster.",
      "Rodillas al ancho de la cadera y hacia el suelo; si se despegan mucho, sube el apoyo.",
      "Brazos sueltos a los lados; sal apoyándote de nuevo en los codos.",
    ],
    beneficios: [
      "Estiramiento profundo de cuádriceps y psoas.",
      "Abre el pecho y el vientre.",
      "Alivia piernas cansadas cuando se hace con apoyo.",
    ],
    precaucion: ["Lesión de rodilla, tobillo o lumbar. No forzar nunca la rodilla."],
  },
  {
    slug: "simhasana", apiId: null, fuente: "propia",
    es: "Postura del león", en: "Lion Pose", san: "Simhasana", trad: "simha = león",
    nivel: "principiante", tipo: ["arrodillada"], zona: ["cuello", "pecho"],
    dinamica: ["quietud"], tema: ["soltar", "energía"],
    img: "Simhasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Sentada sobre los talones, manos en las rodillas con los dedos abiertos.",
      "Inhala por la nariz; al exhalar abre la boca, saca la lengua hacia la barbilla y sopla con sonido 'haaa'.",
      "Lleva la mirada al entrecejo o a la punta de la nariz. Repite 3–5 veces.",
    ],
    beneficios: [
      "Libera tensión de cara, mandíbula y garganta.",
      "Rompe la seriedad de la práctica; suelta el estrés.",
      "Estimula la exhalación completa.",
    ],
    precaucion: ["Molestia de rodilla: siéntate en una silla."],
  },
  {
    slug: "chaturanga-dandasana", apiId: null, fuente: "propia",
    es: "Plancha baja (bastón de cuatro apoyos)", en: "Four-Limbed Staff Pose", san: "Chaturanga Dandasana", trad: "chatur = cuatro, anga = miembro, danda = bastón",
    nivel: "intermedio", tipo: ["equilibrio de brazos"], zona: ["hombros", "core", "muñecas", "pecho"],
    dinamica: ["fuerza"], tema: ["energía", "foco", "transición"],
    img: "Chaturanga-Dandasana low Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Desde plancha, lleva el peso un poco adelante sobre las puntas de los pies.",
      "Baja hasta que los codos formen 90°, pegados al cuerpo; hombros a la altura de los codos, no más abajo.",
      "Cuerpo en una línea firme; si cuesta, baja las rodillas al suelo.",
    ],
    beneficios: [
      "Fortalece hombros, brazos y core.",
      "Transición clave del vinyasa entre plancha y perro boca arriba.",
      "Enseña alineación de hombro que protege la articulación.",
    ],
    precaucion: ["Túnel carpiano, lesión de hombro, muñeca o lumbar. Muy común lesionarse por dejar caer los hombros."],
  },
  {
    slug: "tadasana", apiId: null, fuente: "propia",
    es: "Postura de la montaña", en: "Mountain Pose", san: "Tadasana", trad: "tada = montaña",
    nivel: "principiante", tipo: ["de pie"], zona: ["tobillos y pies", "columna", "core"],
    dinamica: ["quietud"], tema: ["enraizar", "foco", "calma"],
    img: "Tadasana Yoga-Asana Nina-Mel.jpg",
    entrada: [
      "Pies juntos o al ancho de la cadera; reparte el peso entre los cuatro puntos de cada planta.",
      "Rótulas activas sin bloquear, coxis hacia abajo, corona hacia el techo.",
      "Hombros atrás y abajo, brazos a los lados con las palmas al frente. Base de todas las posturas de pie.",
    ],
    beneficios: [
      "Enseña la alineación neutra de toda la práctica.",
      "Mejora la postura y la conciencia del cuerpo.",
      "Aterriza la atención antes de moverse.",
    ],
    precaucion: ["Vértigo o presión arterial baja: separa un poco los pies y abre los ojos."],
  },
];
